feat: report filter by id
CycodeLabs/raven pull request #144
Opened 2023-11-09 16:27 UTC by tal66

closes #126

2023-11-09 18:04 UTC, elad-pticha commented on src/cmdline.py
> +def validate_query_ids(ids_arg) -> list:
I think this part should move to `common` as a util function.

2023-11-09 18:09 UTC, elad-pticha requested changes
LGTM! Please also update the `README.md` with the the new help menu of the reporter.

2023-11-09 19:58 UTC, tal66 commented
done. 
- review: moved the validate function to `utils`
- readme: copied from `-h`

2023-11-12 17:24 UTC, elad-pticha commented
Please rebase from the main branch 🙏

2023-11-12 17:25 UTC, elad-pticha commented on src/common/utils.py
> +def validate_query_ids(ids_arg) -> list:
Can you please add typing for `ids_arg`?

2023-11-12 18:19 UTC, tal66 commented
did the rebase (and squash) and the last request

2023-11-20 12:21 UTC, elad-pticha commented
Hey @tal66,
Thank you for the changes! A quick update: we are working on a CLA agreement before merging this PR.
We will make sure to keep you updated when we are ready.

2024-01-16 09:16 UTC, elad-pticha commented
Hey @tal66,
We created a CLA for new contributors!
Please take a look at our [Contributing Guidelines](https://github.com/CycodeLabs/raven/wiki/Contributing-Guidelines#cla-contributor-license-agreement) for more information.

2024-01-16 09:28 UTC, tal66 commented
strict :)
sent it just now

2024-01-16 09:36 UTC, elad-pticha commented
Great!
Feel free to rebase and fix issues if there's any 🙏

2024-01-22 08:28 UTC, elad-pticha approved these changes
LFTM

2024-01-22 08:30 UTC, elad-pticha commented
Due to branch protection rules, we require all commits to be signed. Can you please make sure to sign the commit?

2024-01-22 11:59 UTC, tal66 commented
oops PR got closed 'cause i renamed the branch, due to a failing test (branch_prefix="^(feat|fix|refactor|chore|docs|test|library)\/[a-z0-9._-]+$"). maybe you can reopen it

2024-01-22 17:46 UTC, elad-pticha commented
For now, it is ok that the convention check is failing. However, It is important the commit will be signed.

2024-01-23 07:53 UTC, elad-pticha commented
Signed commits (using the GPG key) should look like this (contains the verified icon):

<img width="843" alt="image" src="https://github.com/CycodeLabs/raven/assets/124190990/681fa928-5cef-4762-8707-7432a23688f4">

You can read more [here](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) about commit signing.

2024-01-23 10:20 UTC, tal66 commented
ok, created a temp key and now the commit appears to be verified (other repos don't require this)

2024-01-28 10:16 UTC, oreenlivnicode requested changes
Looks great :)
I have requested one change

2024-01-28 10:16 UTC, oreenlivnicode commented on src/config/config.py
> +LAST_QUERY_ID = 16
I'm concerned that when someone adds a new query to the query library, they might forget to update the constant. As I see it, we have two options: make this constant a dynamic variable that reflects the number of query files in the query directory, or introduce a test to ensure the number of queries in the directory matches the constant. 
What are your thoughts?

2024-02-04 14:22 UTC, oreenlivnicode approved these changes
Great!

2024-02-11 10:22 UTC, merged